### ISSUE TITLE
I found a horrible mistake

### ISSUE THREAD

**Issue by kyasabu** [danog/bna#1]
From your README

> I am by no means a biologist, so if you find any (horrible) misteaks in the script, please feel free to contribute by sending a pull request.

>> misteaks

rly hombré ?

**Comment by danog** [comment]
yes


apparently my (py)rony level is over 9000

**Comment by kyasabu** [comment]
Poe's Law is a dangerous thing, @danog

**Comment by danog** [comment]
acknowledged

**Comment by danog** [comment]
Close
